apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-10-04T02:08:51.034753668-04:00"
    description: A Helm chart for the Deployment Manager
    digest: 17bfc2b1ec455eb7330f786e90ca81607e6369ff962d875d268a8fb188ed0b46
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.10.tgz
    version: 2.0.10
generated: "2023-10-04T02:08:51.030749473-04:00"
