apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2023-01-10T13:12:51.527967408-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 9c55bf007c17f268a30a0992b6bb8daf22d0160065e28ec3e1962ef91a94bd6b
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.10.tgz
    version: 2.0.10
generated: "2023-01-10T13:12:51.525236315-05:00"
